### PR TITLE
Current cycle fix

### LINKED ISSUE #35: Fix parser issue
If an event in the event's history has the same transaction_uuid and boot-time as the current event, one of the events will be discarded because of this line: https://github.com/xmidt-org/interpreter/blob/dfb6dfc97c62f385e88a6c414d9622be4e3f4c26/history/eventsParser.go#L211

There should be a more reliable way of determining if an event in the event's history is the same event as the current event.

### LINKED ISSUE #36: Current cycle parser results
The `CurrentCycleParser` should return all events with the same boot-time as the current event, regardless if the event has a birthdate more recent than the current event.

### PR DESCRIPTION
**Pull request by j-mai**
This PR:
* Fixes #35, fixes #36
* Adds event order validator to command line program
* Adds a `TagsToString` method in the validation package

### CODE REVIEW

File: history/eventsParser.go [hunk 1]
```diff
@@ -221,6 +221,45 @@ func parserHelper(events []interpreter.Event, currentEvent interpreter.Event, co
 	return lastCycle, currentCycle, nil
 }
 
+// getSameBootTimeEvents returns a list of events with the same boot-time as the currentEvent, along with the currentEvent.
+// It also runs all of the events in the events list through the comparator, and if the comparator returns true,
+// getSameBootTimeEvents will stop and return an empty slice and the error returned by the comparator.
+// The slice is sorted from newest to oldest.
```
Comment (kristinapathak) [inline history/eventsParser.go:227]:
```suggestion
// The slice is sorted from newest to oldest by birthdate.
```

**Review by kristinapathak — APPROVED** [review]
